/* Generated by the protocol tx_buffer compiler.  DO NOT EDIT! */
/* Generated from: msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msg.pb-c.h"
void   neighbor__init
                     (Neighbor         *message)
{
  static const Neighbor init_value = NEIGHBOR__INIT;
  *message = init_value;
}
size_t neighbor__get_packed_size
                     (const Neighbor *message)
{
  assert(message->base.descriptor == &neighbor__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t neighbor__pack
                     (const Neighbor *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &neighbor__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t neighbor__pack_to_buffer
                     (const Neighbor *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &neighbor__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Neighbor *
       neighbor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Neighbor *)
     protobuf_c_message_unpack (&neighbor__descriptor,
                                allocator, len, data);
}
void   neighbor__free_unpacked
                     (Neighbor *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &neighbor__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor neighbor__field_descriptors[2] =
{
  {
    "dst_ip",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Neighbor, dst_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Neighbor, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned neighbor__field_indices_by_name[] = {
  0,   /* field[0] = dst_ip */
  1,   /* field[1] = mac */
};
static const ProtobufCIntRange neighbor__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor neighbor__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "neighbor",
  "Neighbor",
  "Neighbor",
  "",
  sizeof(Neighbor),
  2,
  neighbor__field_descriptors,
  neighbor__field_indices_by_name,
  1,  neighbor__number_ranges,
  (ProtobufCMessageInit) neighbor__init,
  NULL,NULL,NULL    /* reserved[123] */
};
