/* Generated by the protocol tx_buffer compiler.  DO NOT EDIT! */
/* Generated from: msg.proto */

#ifndef PROTOBUF_C_msg_2eproto__INCLUDED
#define PROTOBUF_C_msg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Neighbor Neighbor;


/* --- enums --- */


/* --- messages --- */

struct  Neighbor
{
  ProtobufCMessage base;
  uint32_t dst_ip;
  ProtobufCBinaryData mac;
};
#define NEIGHBOR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&neighbor__descriptor) \
    , 0, {0,NULL} }


/* Neighbor methods */
void   neighbor__init
                     (Neighbor         *message);
size_t neighbor__get_packed_size
                     (const Neighbor   *message);
size_t neighbor__pack
                     (const Neighbor   *message,
                      uint8_t             *out);
size_t neighbor__pack_to_buffer
                     (const Neighbor   *message,
                      ProtobufCBuffer     *buffer);
Neighbor *
       neighbor__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   neighbor__free_unpacked
                     (Neighbor *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Neighbor_Closure)
                 (const Neighbor *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor neighbor__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_msg_2eproto__INCLUDED */
